# Generated by Django 5.2.4 on 2025-07-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="choise",
        ),
        migrations.AddField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="todo",
                max_length=30,
            ),
        ),
    ]
