# Generated by Django 5.2.4 on 2025-07-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_tasks_choise_tasks_due_date_tasks_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
