# Generated by Django 5.2.4 on 2025-07-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_tasks_completed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
